default_agent: ops_ai_agent
agents:
  ops_ai_agent:
    name: ops_ai_agent
    language: python
    node_version: null
    entrypoint: /home/ubuntu/AI-Ops-Agent-AgentCore/agentcore/runtime/entrypoint.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::057716757052:role/OpsAgentBedrockAgentCoreRole-us-east-1
      execution_role_auto_create: false
      account: '057716757052'
      region: us-east-1
      ecr_repository: 057716757052.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-ops_ai_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: ops_ai_agent-EgxPs5Arss
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:057716757052:runtime/ops_ai_agent-EgxPs5Arss
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-ops_ai_agent-builder
      execution_role: arn:aws:iam::057716757052:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-5d5dd51712
      source_bucket: bedrock-agentcore-codebuild-sources-057716757052-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
